### ISSUE TITLE
default zoom

### ISSUE THREAD

**Issue by bogdankol** [open-source-labs/Svelvet#105]
I think that current default zoom is good when there are not much of nodes, but if its gonna be hundred of them - it would be helpful to have a possibility to prescribe default zoom level

**Comment by emmanotly** [comment]
Hi @bogdankol sorry for the late response, I have been newly added to the Svelvet 5.0 team. 

I'm happy to let you know that this current Svelvet team has successfully created a default zoom feature, but would you mind elaborating on your request so I can make sure that your suggestion is encompassed in our improved default zoom?

We will be launching the new version of Svelvet early next year, and hope you have an opportunity to review this feature. I look forward to your continued feedback!

Cheers!

**Comment by taylien96** [comment]
This is now possible in svelvet 5.0! go on and check the docs!!
