### ISSUE TITLE
custom nodes

### ISSUE THREAD

**Issue by bogdankol** [open-source-labs/Svelvet#106]
And I thought that it would be really helpful to have a feature of creating custom nodes: like nodes with lists in it, with some svgs/images and different styled texts, different nodes with different styles (for example in React Flow it could be made with the help of node types). Also a little bit more possibilities to edit Hadlers (connection dots) would be helpful too. For example: be able to prescribe its border and background-color :)

**Comment by ronvoluted** [comment]
You can modify Svelvet a bit to do your bidding and support this: https://github.com/open-source-labs/Svelvet/issues/112#issuecomment-1275923588
