### ISSUE TITLE
Snap to Grid (enhancement)

### ISSUE THREAD

**Issue by sanderjson** [open-source-labs/Svelvet#107]
Congratulations with 2.02, and thank you for your work! 🎉🤩

I would like to have a snap to grid option if possible.

`<Svelvet {nodes} {edges} grid gridSnap={true} />` or

`<Svelvet {nodes} {edges} background backgroundSnap={true} />`

**Comment by ianhnizdo** [comment]
It has now been implemented! Thank you for your feedback sanderjson!
