### ISSUE TITLE
How to read the new position of nodes after drag

### ISSUE THREAD

**Issue by ak4zh** [open-source-labs/Svelvet#108]
When the user moves a node its new position is not getting updated back In the input JSON data.
I have tried to bind it and use stores, but it seems the data update is not supported.

This feature is helpful because I want to render back the same flowchart that the user has customized when he visits the app next time.

I am unable to find this info in the docs.

**Comment by sher85** [comment]
@ak4zh where are you experiencing this issue, [REPL](https://www.svelvet.io/playground/) on the selvet.io website? Can you share a screenshot/gif?

**Comment by ak4zh** [comment]
I want to get the new co-ordinates of the nodes so I can save it in a store and render the samediagram again which user created by dragging the nodes.
I did not find any info about getting the x,y coordinates of the node once it has been dragged by the user.

**Comment by pbxothi** [comment]
@ronvoluted thanks for the quick fix. This is useful. However, the callback is not triggered when dragged on a touch screen.

**Comment by taylien96** [comment]
There is now a way to get the json and upload it with an updated diagram to share changes between users!

**Comment by franciswillian91** [comment]
same problem here, i need to save node locations after dragging and arranging my flow but i don't know how to get those properties once done. 
@taylien96 you mentioned that there is a way to do this but i didn't find it.

**Comment by gurmeet-bluesheets** [comment]
@franciswillian91 I think @taylien96 is referring to this https://www.svelvet.io/docs/importDiagrams/

**Comment by gurmeet-bluesheets** [comment]
@ronvoluted , @taylien96 how to handle this in the latest version?

**Comment by franciswillian91** [comment]
@gurmeet-bluesheets, sure makes sense i didn't discover that feature, mb ;D

**Comment by rungdung** [comment]
Indeed, I would like a built in way to persist diagrams or documentation on how to retrieve it from the store

**Comment by briangregoryholmes** [comment]
Closing as this has fundamentally changed in Svelvet v7 and up. That said, smoothing out the DX is an active area for us. The position prop can be "bound" to using bind:position for programatic read/write access.
