### ISSUE TITLE
Fixed graphs

### ISSUE THREAD

**Issue by dvisockas** [open-source-labs/Svelvet#114]
Hey,
Is there a way to fix the graph in place? i.e. to disable `mousemove`  and `touchmove` events.
I'd be happy to open a PR that would implement `export movementEnabled = true` if you agree that this would be a good addition.

**Comment by sameev** [comment]
Hi - This sounds like a great addition to the existing functionality. Feel free to open a PR and we can review / merge. Thanks!

**Comment by SvelvetOSLabs** [comment]
Hi - This sounds like a great addition to the existing functionality. Feel free to open a PR and we can review / merge. Thanks!
