### ISSUE TITLE
Version 3 breaking sveltekit

### ISSUE THREAD

**Issue by dvisockas** [open-source-labs/Svelvet#119]
Updating svelvet to version 3 breaks sveltekit. When starting a server just throws 11 `cound not resolve "<package_name>"` errors. Downgrading to a version `<3` fixes the problem.

Steps to reproduce:
```bash
npm create svelte@latest test-svelvet
cd test-svelvet
npm install
npm install svelvet
npm run dev -- --open
```

Error:
```
> test-svelvet@0.0.1 dev
> vite dev "--open"


  VITE v3.1.1  ready in 481 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
✘ [ERROR] Could not resolve "bluebird"

    node_modules/node.env/api.js:122:19:
      122 │   Promise = require('bluebird');
          ╵                     ~~~~~~~~~~

  You can mark the path "bluebird" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

```

**Comment by mr-islam** [comment]
Can confirm the same issue 

Is there any timeline for this being fixed? I really need the `movement=false` attribute for a project, but that doesn't seem to be in v2...

**Comment by RonB** [comment]
I also got an error that directory imports are not supported. I changed the index.js and imported the types per file:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/559779/195813419-8fdd0556-556b-4c04-8f37-4afdc375715b.png">

**Comment by aubertlone** [comment]
Hello Ronald! I just wanted to mention that while there is Github repo for Svelvet, that is mainly for the website. In this particular issue, we were discussing the npm package svelvet. perhaps try 'npm install svelvet' and then follow the steps outlined in my temporary fix.

Then you can change your import statement to import Svelvet from 'svelvet'. I hope these steps help you get svelvet up & running!
