### ISSUE TITLE
Disable node dragging

### ISSUE THREAD

**Issue by adam-kov** [open-source-labs/Svelvet#146]
*I didn't find anything in the docs about disabling the dragging of nodes, so feel free to close the issue if it's an implemented feature.*

I would like to have the option to disable the dragging on the individual nodes, but still keep the paning and zooming on the wrapper.

I propose two ways to achieve this:

1. Set a property on each Node *(`locked` for example)*:
```ts
{
  id: 1,
  position: { x: 0, y: 0},
  data: { label: "Label" },
  width: 100,
  height: 40,
  locked: true
}
```

2. Set an attribute on the `Svelvet` component itself *(`lockNodes` for example)*:
```html
<Svelvet {nodes} {edges} background lockNodes />
```

**Comment by taylien96** [comment]
This is now possible in svelvet 5.0! go on and check the docs!! prop "isLocked"
