### ISSUE TITLE
Programatic location & zoom

### ISSUE THREAD

**Issue by jycouet** [open-source-labs/Svelvet#147]
First, thx a lot for this great project 🥳
I built a visual selection tree that look like: 
![image](https://user-images.githubusercontent.com/5312607/201524569-ed0d9bc1-3c1b-4dd9-8db3-ae7555c84f36.png)
Where users can extend alone the tree with custom rules & co! Quite fun :)

The issue is that today, it's always opening on "top left". Could we set the location & zoom on load?

Thx for your help

**Comment by msze400** [comment]
I second this! This would be super helpful!

**Comment by taylien96** [comment]
Hey guys, we finished up a default zoom and pan feature to be released on svelvet 5.0! Look forward to it on launch and I'll close this then!

**Comment by msze400** [comment]
Awesome thank you!!! looking forward to it!!!

**Comment by taylien96** [comment]
This is now possible in svelvet 5.0! go on and check the docs!!
