### ISSUE TITLE
clickCallback event giving the wrong node

### ISSUE THREAD

**Issue by jycouet** [open-source-labs/Svelvet#148]
I'm upgrading from `2.0.2` to `4.0.3` and I noticed a change in the `node.clickCallback` function.

In 2.0.2, when I click on a node the event fire, and I get the right `node.id`. If I click somewhere else, nothing happen.
In 4.0.3, when I click on a node the event fire, and I get the right `node.id`. If I click somewhere else (anywhere), an even fire again with the last `node.id`.

I'm staying on v2.0.2 for now.

**Comment by taylien96** [comment]
Weird, we can't seem to recreate this, can you give me the situation or instance of svelvet where this was happening?

**Comment by jycouet** [comment]
I would like to help, but I don't get the question. Sorry ><

**Comment by taylien96** [comment]
This is now fixed in svelvet 5.0! go on and check the docs!!

**Comment by taylien96** [comment]
This is now fixed in svelvet 5.0
