### ISSUE TITLE
Feature:change cursor type when hover on node

### ISSUE THREAD

**Issue by venom90** [open-source-labs/Svelvet#150]
There needs to be a property on Node to change the cursor type like a pointer, pencil, etc.

**Comment by venom90** [comment]
I can do this with 

```
.Node > .Node:hover {
    cursor: pointer;
}
```
in app.css. But it will be nice if we get this option in the code itself. To set it dynamically.

**Comment by briangregoryholmes** [comment]
This can be set dynamically when creating custom Nodes in Svelvet 7, but we'll consider adding a hover cursor prop to use with default nodes. Thanks!
