### ISSUE TITLE
Feature:Load custom svelte component as Node

### ISSUE THREAD

**Issue by venom90** [open-source-labs/Svelvet#151]
Feature request: A Node can be a svelte component.

Example:

```
<script lang="ts">
     import CustomSvelteComponent from '$lib/components/CustomSvelteComponent';

     const initialNodes: Node[] = [{
	id: 1,
	position: { x: 100, y: 100 },
	data: { component: CustomSvelteComponent},
	width: 80,
	height: 80,
	bgColor: 'white',
	borderColor: 'transparent',
	borderRadius: 5,
	sourcePosition: 'right',
	targetPosition: 'left',
}];
</script>

```

**Comment by Kinthamen** [comment]
How do I work on this? Do I just fork and work on it that way or some other way? I already have a solution to this, just working out an error with typescript not linking the customNodes export. :(

**Comment by timmylem01** [comment]
Hey venom90, I'm apart of the Svelte 5.0 team and wanted to reach out to you regarding this feature request. Are you able to elaborate a bit on what kind of custom svelte components you are trying to make nodes with? Can the components be as simple as a single button? Also, thank you for using Svelvet!

**Comment by Kinthamen** [comment]
Due to the nature of storing things in the svelte store, I am not sure how well passing a component in the data field would work, but doing something like reactflow might be a good solution.

Example:

<script lang="ts">
     import Svelvet from 'svelvet';
     import CustomSvelteComponent from '$lib/components/CustomSvelteComponent';

    const customNodes = [
        {
            customSvelteComponent: CustomSvelteComponent
        }
    ]

     const initialNodes: Node[] = [{
	id: 1,
	position: { x: 100, y: 100 },
       type: 'customSvelteComponent',
	data: { label: 'My Custom Component' },
	width: 80,
	height: 80,
	bgColor: 'white',
	borderColor: 'transparent',
	borderRadius: 5,
	sourcePosition: 'right',
	targetPosition: 'left',
}];
</script>

<Svelvet {customNodes} ...>

At this point the customNode just needs to take in the node object created in the GraphView and present the data as needed.

**Comment by emmanotly** [comment]
Hi @venom90 and @Kinthamen, I am on the Svelvet 5.0 team with @timmylem01 and wanted to reach back out;

We have implemented a feature that we believe satisfies this suggestion, and currently are working out some of the edge cases to make it as good as we are able to.

As always, thank you for your suggestion, Svelvet 5.0 team's main goal is to implement features to better improve UI and UX.

We look forward to hearing what you think after we launch the new version of Svelvet!

Cheers!

**Comment by rohanrajpal** [comment]
I was also wondering if this is possible. My use case is that I was wondering if we can make a worflow builder like Manychat with Svelvet? Something like this basically

<img width="812" alt="image" src="https://user-images.githubusercontent.com/7023147/208286175-f8c50276-10b2-4dce-90c3-a6601a151413.png">

I guess after rendering of custom svelte components is allowed, this would be a possibility? But probably still difficult and dragging and dropping edges around is something I guess might not be possible with Svelvet just yet.

Anyhow thanks a lot for this wonderful library! And do let me know if building something like above is possible, and if I can help in any way.

**Comment by timmylem01** [comment]
Hey @rohanrajpal, thank you for the kind words and continuing to use Svelvet! My team and I have been working on another feature that may be something you are looking for. [](url)
![demo](https://user-images.githubusercontent.com/103241084/208490930-2f8afcaf-0a77-41f7-b8fa-09a486dca9b3.gif)

**Comment by Kinthamen** [comment]
This looks awesome! 

So, I hear a lot about the 5.0 team. 

Is this some kind of secret repo? Is there an "upcoming" list somewhere? 

I'd like to help, but don't want to double up work. 😃

**Comment by rohanrajpal** [comment]
> Hey @rohanrajpal, thank you for the kind words and continuing to use Svelvet! My team and I have been working on another feature that may be something you are looking for. ![demo](https://user-images.githubusercontent.com/103241084/208490930-2f8afcaf-0a77-41f7-b8fa-09a486dca9b3.gif) [ ![demo](https://user-images.githubusercontent.com/103241084/208490930-2f8afcaf-0a77-41f7-b8fa-09a486dca9b3.gif) ](https://user-images.githubusercontent.com/103241084/208490930-2f8afcaf-0a77-41f7-b8fa-09a486dca9b3.gif) [ ](https://user-images.githubusercontent.com/103241084/208490930-2f8afcaf-0a77-41f7-b8fa-09a486dca9b3.gif)

This is just I would want! Looking forward to 5.0 :))

**Comment by taylien96** [comment]
This is now possible in svelvet 5.0! go on and check the docs!!
