### ISSUE TITLE
Feature request - add `className` to Containers and Edges

### ISSUE THREAD

**Issue by Evanfeenstra** [open-source-labs/Svelvet#153]
Awesome library!

Simply adding a custom class to containers and to edges is all that is needed to make svelvet much more customizable. I think most use cases for svelvet have different "categories" (classes) of containers and edges. I would love things like opacity, cursor, dashed border, box-shadow, and many more on my nodes!

Any thought on this? Worth it for me to work on a PR? Or are you more interested in going all the way (Svelte component or HTML template)

**Comment by emmanotly** [comment]
Hi @Evanfeenstra !


Thank you so much for this request! Feedback and update suggestions are always welcomed and so much appreciated! I am on the Svelvet 5.0 team; this is an awesome suggestion that we will be working on, among other great features for a more customizable and intuitive UI! Keep an eye out for a great new version of Svelvet coming soon!

- Emma Ferguson
- Svelvet 5.0

**Comment by Evanfeenstra** [comment]
hi @emmanotly 

Thanks for adding this to svelvet 5! But when I add `className` to a node, i see a an Uncaugh Error in the JS console ` Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules`

And the page becomes unresponsive

**Comment by taylien96** [comment]
This is now possible in svelvet 5.0! go on and check the docs!!

**Comment by Evanfeenstra** [comment]
If anyone else has the bug above, i fixed it by using `vite js` instead of `degit` to initialize the app

**Comment by taylien96** [comment]
Hmmm, Our team tested in vite and degit it should work in both, I'll reopen for now

**Comment by dilignt** [comment]
I can't see className as a new property in the Custom Edges docs.  I need to be able to select both nodes and edges so I can interactively set the display/visibility to create layers of nodes and edges that can be hidden and shown.  It was already possible to select the nodes for this purpose using the id attribute, but I can't see any way to select the edges and handles so that when hiding a pair of linked nodes the edge will also be hidden.  

Please help

**Comment by taylien96** [comment]
We didn't get to setting a classname for edges, however you should be able to reach the edges in CSS doing something like this, I'm sorry it isn't currently easier, but i hope this helps somewhat in the meantime:
```
.Svelvet > .Edges > g > path {

}
```

**Comment by Evanfeenstra** [comment]
that doesn't help if you have different types of edges, that you want to style differently

**Comment by dilignt** [comment]
Yes @Evanfeenstra  that's correct - I need to be able to select and hide individual edges, not all of them at once.  @taylien96 - the only way I can think of doing this is either you add an id attribute to the edges like the nodes, or individuallly configurable class attribute to select the edges that way.  Unless I'm missing something else?

Also - is there any way to hide the handles in v5 when not doing nodeCreate/Link ?

Awesome library btw.

**Comment by michael-chiang-dev5** [comment]
Hi @Evanfeenstra,

Svelvet6 has implemented custom css for edges! You can try it out here: https://stackblitz.com/edit/node-classes?file=src/routes/+layout.svelte

Closing ticket, but if you have any questions / bug reports please re-open. Thank you for your support!
