### ISSUE TITLE
Roadmap to 5.0

### ISSUE THREAD

**Issue by bruxor** [open-source-labs/Svelvet#159]
Reading some of the comments, it seems that the team is working on version 5.0.

Could you share a roadmap with the expected features and an expected timeline for the release? I see that many people are keen to contribute (myself included) and doing so would allow contributors to better know:
- what to prioritise
- what to expect for the next release and by when

Ideally, we could label the issues necessary for 5.0 with a specific label.

**Comment by timmylem01** [comment]
Hey bruxor, we actually just launched svelvet 5.0 this morning! We're going to start closing issues that the update fixed/completed.
