### ISSUE TITLE
Missing props in type declaration of the container

### ISSUE THREAD

**Issue by bruxor** [open-source-labs/Svelvet#163]
The new props that have been added to the Svelvet container component seem to be missing from the [type declaration](https://github.com/open-source-labs/Svelvet/blob/main/NPM%20Package/svelvet/Containers/Svelvet/index.svelte.d.ts).

<img width="164" alt="image" src="https://user-images.githubusercontent.com/1772174/210973823-d51407e7-25b4-4c33-bf3b-194a1926a7c4.png">

**Comment by taylien96** [comment]
Issue should be fixed as of svelvet 5.0.2

**Comment by yordiverbeeck** [comment]
Thanks for the update! @taylien96 
One extra one I've found was a missing "className" in the Node type.

**Comment by taylien96** [comment]
We believe we have gotten all typing errors, we will leave this open in case more are found

**Comment by taylien96** [comment]
Closing issue for now
