### ISSUE TITLE
Active edge in empty space when linking a node to itself

### ISSUE THREAD

**Issue by yordiverbeeck** [open-source-labs/Svelvet#165]
Possible bug: 
As shown in the video, it's possible to link a node to itself. In that case the animation edge stays active and is fixed to the position in the scene. 

https://user-images.githubusercontent.com/10527767/211008851-bb20fff4-109e-4403-a0c9-0aaf286b1310.mov

**Comment by dmckenna44** [comment]
Thanks for catching that bug! the package has just been updated, v5.0.4 should be free of this issue
