### ISSUE TITLE
Pass props to custom Svelte components

### ISSUE THREAD

**Issue by kbrgl** [open-source-labs/Svelvet#174]
Hi there!

I’m trying to use this library to generate a graph visualization of a data-flow. I would like to generate this graph using some existing components that take props.

I know I can use custom components without props using `data: { custom: MyComponent }`, but is it possible to pass props to MyComponent? Maybe using something like `data: { custom: MyComponent, props: { ... } }`?

**Comment by zacharygriffee** [comment]
Completely agree! Having the ability to pass attributes is crucial for composition! This is the way I get around the limitation.

<h3>At top of .svelte</h3>

```
<script context="module">
    class Wrapper {
        constructor(ComponentClass, options = {}) {
            const {
                props = {}, events = {}
            } = options;
            // could do this.componentClass and then return that
            // in the nodes object, but this is more concise imo.
            return class extends ComponentClass {
                constructor(options) {
                    options.props = {
                        ...options.props,
                        ...props
                    };

                    super(options);
                    // Top level event dispatchers in component could be missed. So may need to defer dispatchers in component.
                    this.$$.callbacks = events;
                }
            }
        }
    }
</script>
```

<h3>In Svelvet nodes</h3>

 ```
let nodes;

onMount(async () => {
        nodes = [
            {
                id: 1,
                position: {x: 50, y: 50},
                data: {
                    custom: new Wrapper(
                        YourComponentHere,
                        {
                            props: {
                                obiwan: "I'm one with the force",
                            },
                            events: {
                                "houston": [({detail}) => onMessage]  // Make note that this is an array of functions
                            }
                        }
                    )
                },
                width: 200,
                height: 200,
                bgColor: "white"
            }
        ]
    });
    function onMessage({detail}) {
        console.log(detail);
    }
```


<h3>And initiate the svelvet component</h3>

```
{#if !!nodes}
    <svelvet {nodes}/>
{/if}
```

**Comment by kbrgl** [comment]
Thanks for the workaround! It's a little hacky so it would be nice to get official support, but this will do nicely while I wait for that!

**Comment by Romiros82** [comment]
Completely agree! 
Can I have a working example of this hacker approach? I could not get.

**Comment by zacharygriffee** [comment]
I should be able to write up a repl within the week.

**Comment by zacharygriffee** [comment]
> Completely agree! Can I have a working example of this hacker approach? I could not get.

Paste this in the svelvet repl (the 'playground') .Didn't see an option to save it.

I'm using the 'qrcode' for simplicity. You can import your own svelte components and pass it in the nodes.data property. I used a class 'Wrapper' but you could easily just use a function instead. to be less hackish.

```
<script context="module">
    class Wrapper {
        constructor(ComponentClass, options = {}) {
            const {
                props = {}, events = {}
            } = options;
            // could do this.componentClass and then return that
            // in the nodes object, but this is more concise imo.
            return class extends ComponentClass {
                constructor(options) {
                    options.props = {
                        ...options.props,
                        ...props
                    };

                    super(options);
                    // Top level event dispatchers in component will be missed. 
                   // So defer dispatchers in component with onMount or tick.
                    this.$$.callbacks = events;
                }
            }
        }
    }
</script>

<script>
	import {onMount} from "svelte";
	import Svelvet from "svelvet";
	let nodes;
	let edges = []; // The svelvet component needs this.

	onMount(async () => {
		const QRComponent = (await import('https://cdn.jsdelivr.net/npm/svelte-qrcode')).default
		
		nodes = [
			{
				id: 1,
				position: {x: 50, y: 50},
				data: {
					custom: new Wrapper(
						QRComponent,
						{
							value: "Svelvet is a secret obsession of mine."
						}
					)
				},
				width: 200,
				height: 200,
				bgColor: "white"
			}
		]
	});
	function onMessage({detail}) {
		console.log(detail);
	}
</script>

{#if !!nodes}
    <Svelvet {nodes} {edges} />
{:else}
    I have a secret for you.
{/if}
```

**Comment by Romiros82** [comment]
Thanks a lot!!!

**Comment by eliasdefaria** [comment]
The workaround you provided doesn't work in server side rendered cases with SvelteKit. Would be great to be able to pass props! Perhaps this is a use case for something like [Svelte Render](https://github.com/bryanmylee/svelte-render)

**Comment by zacharygriffee** [comment]
> The workaround you provided doesn't work in server side rendered cases with SvelteKit. Would be great to be able to pass props! Perhaps this is a use case for something like [Svelte Render](https://github.com/bryanmylee/svelte-render)

Yeah I forgot to mention that. It is client render only. But that is mainly my use case and haven't explored a way to do it with ssr. Maybe I'll tinker to see if I can get it to work but my plate is very busy. So svelvet working out prop passing to the custom component would be ultimately the hope and having a better way to get 'self' component for forwarding context, props, slots and events on the pure svelte/svelte kit side would be icing on the cake.
