### ISSUE TITLE
Feature Requests; edge and node events, etc

### ISSUE THREAD

**Issue by zacharygriffee** [open-source-labs/Svelvet#175]
Great App! I had to try it out as soon as I learned about it. 

While the library is very simple and great for what is explicitly intended for, it also has little flexibility to out side of the box use case.I have some feature requests that I believe would make it really flexible without too much work. 

- More events or reactions$. The edges don't emit anything. And the only event the node has is a click.  
- cancel edge creation if criteria not met. 
- user resizable nodes by dragging edge 
-  API documentation. While the docs now are very helpful... API docs would be very helpful for a developer that needs more granular control.

Again my use case is particular. If your your mind set is do one job and do it well then yes very good job on this app.

**Comment by ErnestoGonza** [comment]
Hey @zacharygriffee, as it stands we still have not incorporated all of the requests here, however as of Svelte 6.0 we did add resizable nodes, just hover over the bottom right corner of a node to see a resize drag option. We also made the connectors more flexible, giving you the option to dictate where each of the anchors will connect by setting a targetPosition (left, right, top, bottom). If you don't assign a targetPosition the anchors will now be dynamically rendering to the closest side from it's target node. I have attached here a stackblitz link to display some of the changes we have made so you can play around with it and let us know what you think. We are always trying to improve upon Svelvet so all of the feedback is appreciated! I'll leave this open as a note to us for when we are ready to tackle some of these other requests (P.S API documentation is in the works but not at a place where we are happy with it just yet.) https://stackblitz.com/edit/sveltejs-kit-template-default-nhrddn?file=src/routes/+layout.svelte
