### ISSUE TITLE
Feature: is SupaBase user authentication needed?

### ISSUE THREAD

**Issue by ya-johnson** [open-source-labs/Svelvet#180]
Hello,
Just noticed that the feature of auth through github is not doing anything, is this something for future use?

**Comment by taylien96** [comment]
It save diagrams you created on the REPL

**Comment by ya-johnson** [comment]
Thanks,

I think its a little bit useless tbh, cant imagine myself ever using this. 
But i do think that a set of good examples on the repl page would be much more helpful.
I could work on that, but i will remove supabase.

So should i just do it and open pull request for that? or this feature is something of importance ...
(thanks again, i just never committed to open project before)

**Comment by yordiverbeeck** [comment]
@ya-johnson Agreed!
I think it would be a good move if the project is split up into multiple repositories: Svelvet library & Svelvet website.
It confuses my IDE and would make contributions a lot more accessible in general.

**Comment by ya-johnson** [comment]
@yordiverbeeck Say no more!

I have couple of ideas for the Svelvet website, which i wish i could discuss with someone.
Anyway, i do also think that the repo is quiet messy, there is a lot of unused or unnecessary stuff,
for example the $lib folder is untouched. But in overall the repo needs some organization.

So i may just do some cleaning while i work on features for the Svelvet website:
- new landing page
- dark mode
- repl examples (remove supabase)
- improve documentation

As i mentioned, i am not used to committing to open projects so i guess i will just make pull requests and see.
