### ISSUE TITLE
Feature request: Unfold and collapse

### ISSUE THREAD

**Issue by Praktikant-GPJoule** [open-source-labs/Svelvet#183]
Hello Guys,

I would like to know if it's possible to Unfold/Collapse a node and there Children.

Thank you!

**Comment by horaciovallejo** [comment]
Hello @Praktikant-GPJoule ,

**Comment by horaciovallejo** [comment]
Hello @Praktikant-GPJoule, thank you for reaching out to us with your feature request. I'm happy to inform you that the ability to unfold/collapse a node and its children has been implemented in the latest version of our library.

Click [here](https://stackblitz.com/edit/sveltejs-kit-template-default-qvd72u?file=src/routes/+layout.svelte) for a sandbox showing how to use this feature.

We appreciate your interest in Svelvet and value your feedback. Thank you for helping us make our product better for every engineer to enjoy.

If you have any questions or need further assistance, please don't hesitate to reach out.

**Comment by KiraPC** [comment]
@horaciovallejo Hi is this feature removed in the new version or is there a new way to enable it?
