### ISSUE TITLE
Edit edges

### ISSUE THREAD

**Issue by robinsonkwame** [open-source-labs/Svelvet#184]
The `nodeEdit` property allows you to edit various properties of a node using a pop up modal. Edges also contain various properties. It would be wonderful if there was an `edgeEdit` or `editable` prop or that we could pass in to `Svelvet` and use the same modal for editing edges.

**Comment by rachelheplus** [comment]
Hi @robinsonkwame  ,

Svelvet 6 team has removed nodeEdit property and added editable prop instead. Now when you pass `editable = {true}` prop into the Svelvet component, it will enable both node edit and edge edit. Below is a Stackblitz link for how to implement this new feature:
https://stackblitz.com/edit/svelvet6-edge-edit?file=src/routes/+page.svelte

You can also see a quick demo in the gif below:
![feature_node_edge_edit](https://user-images.githubusercontent.com/30616327/217675318-a3fd616d-8bba-4a30-9d66-0d7c8b322477.gif)
