### ISSUE TITLE
Links to Svelvet twitter aren't working

### ISSUE THREAD

**Issue by yordiverbeeck** [open-source-labs/Svelvet#189]
Does Svelvet have an official Twitter account? 
The ones linked on the github page AND the website leads to an invalid account 
https://twitter.com/svelvet_oslabs

**Comment by horaciovallejo** [comment]
Hello!

**Comment by horaciovallejo** [comment]
Hello, looks like our old Twitter was deactivated. We updated the Github and website links to the new account!! Thank you for letting us know! here is the new official Twitter https://twitter.com/SvelvetOSLabs
