### ISSUE TITLE
Documentation examples broken

### ISSUE THREAD

**Issue by yordiverbeeck** [open-source-labs/Svelvet#201]
Hi team! Thanks for the hard work on getting 6.0 out!
However, it seems that all the examples on the documentation are broken and result in an error now. 😅

Just open any doc on the Svelvet website, example: https://www.svelvet.io/docs/core-concepts/

Error
![image](https://user-images.githubusercontent.com/10527767/217631225-29f3bb40-d421-4802-826c-18c2fb853df9.png)

**Comment by michael-chiang-dev5** [comment]
Hi @yordiverbeeck,

Thanks for letting us know! It is an issue with CodeSandbox; since yesterday there have been problems with d3-zoom imports. We have submitted a bug report and hope it gets fixed but will replace the demos with StackBlitz if issues continue.

Thanks for the heads up!

**Comment by TensionCoding** [comment]
Also I am experiencing an issue on the REPL since the 6.0 release
![Screenshot 2023-02-08 at 2 07 09 PM](https://user-images.githubusercontent.com/103322358/217634337-19df1da2-99dc-4e91-ae31-5efcb17abb43.png)

**Comment by michael-chiang-dev5** [comment]
> Also I am experiencing an issue on the REPL since the 6.0 release ![Screenshot 2023-02-08 at 2 07 09 PM](https://user-images.githubusercontent.com/103322358/217634337-19df1da2-99dc-4e91-ae31-5efcb17abb43.png)

We will replace REPL with StackBlitz for now while we get things working again

**Comment by yordiverbeeck** [comment]
@michael-chiang-dev5 Cool, thanks for the quick reply!

**Comment by michael-chiang-dev5** [comment]
All documentation examples have been replaced with StackBlitz, or displayed directly with Svelvet component. Repl is also working. The CodeSandbox issue persists; this is an issue with CodeSandbox and all Svelvet versions (1-6) are failing. A ticket has been filed with codeSandbox.

Thanks for the heads up! closing ticket
