### ISSUE TITLE
Does initialLocation and initialZoom support reactive functionality?

### ISSUE THREAD

**Issue by msze400** [open-source-labs/Svelvet#214]
Hi Svelvet Team,

Love the feature updates so far. Running into a few issues though; I'm unsure if this was intended functionality was considered or if I'm implementing this incorrectly.

I have a Svelvet component I'm currently implementing like this:

`<Svelvet nodes={$SvelvetNodes} minimap={true} edges={$SvelvetEdges} width={innerWidth*8/12.4} height ={1000} background initialLocation={$searchNode.position} initialZoom={0}></Svelvet> `

Since we have lots of nodes I was hoping to implement a filterable tabular view of all the nodes to make it more manageable. I was hoping to have the user click on the node and update the search node position and have the pan area snap to the node position.

Does the initialLocation/intialZoom property account for reactivity?

Also our team is currently on v5.0.8 (you guys are churning out releases and we can't keep up!)

**Comment by michael-chiang-dev5** [comment]
Hi @msze400,

Thank you for your comment! After testing, it appears data reactivity for initialLocation/initialZoom is not implemented in 6.0.2, but that is definitely something that we want! We will try to roll it out next patch.

5.0.8 seems to have the same problem, however our priority is fixes for v6.

Thank you for the report! Leaving ticket open until resolved.

**Comment by msze400** [comment]
Thanks for the quick response @michael-chiang-dev5 , you guys are rock stars 👍

**Comment by michael-chiang-dev5** [comment]
We have implemented data reactivity for zoom/initial position in Svelvet 6.0.4

Test it here: https://stackblitz.com/edit/data-reactivity?file=src/routes/+layout.svelte

Closing ticket, but if you have any questions / suggestions (especially about zoom) please don't hesitate to reopen or open new ticket. Thank you for supporting Svelvet!
