### ISSUE TITLE
Minimap Unable to Click to Area with v6 Deployment

### ISSUE THREAD

**Issue by msze400** [open-source-labs/Svelvet#216]
Hi Svelvet Team!

Just noticed while I was clicking through the minimap feature on the v6 deployment (https://www.svelvet.io/docs/Minimap/) that clicking on the minimap now fails to pan to the new area.

This was working in the v5.0.8 release but not sure what else could be affecting this with the v6 release. Just wanted to make sure it was on your radar because we do implement the minimap now!

**Comment by michael-chiang-dev5** [comment]
Thank you for the bug report! Super useful for us as we generate more unit tests so we know what to look out for.

The bug has been fixed in the latest npm package 6.0.3 (see sandbox https://stackblitz.com/edit/minimap-as34t2?file=package.json)

Thank you for your support!
Closing ticket
