### ISSUE TITLE
Svelvet.io mobile site is broken

### ISSUE THREAD

**Issue by andrew-widjaja** [open-source-labs/Svelvet#218]
Tapping links/buttons doesn't work on mobile, so I can't navigate the site.

**Comment by rachelheplus** [comment]
Hi Andrew,
Thanks for your input!
The website should have been fixed on mobile now.  Give it a try and let us know if there's any issue. We appreciate your feedback!

**Comment by andrew-widjaja** [comment]
Works great, thanks for the quick fix! 🙌🏻
