### ISSUE TITLE
Misc documentation site suggestions

### ISSUE THREAD

**Issue by andrew-widjaja** [open-source-labs/Svelvet#219]
Not an issue but rather than having each feature be given its own tab under "Guides", it could be neater to consolidate related features into categories since the list is growing and becoming less intuitive for users.

Also would be good to not use language like "feature A is now available!" or "Svelvet can now..." in the actual docs (these are more for release announcements, changelogs etc). It should sound like all features came together.

**Comment by michael-chiang-dev5** [comment]
Hi @andrew-widjaja 

Recognize your name from the git log history, nice to see an OG member of Svelvet!

I agree the user docs need to be improved; the website itself has accumulated quite a bit of debt and at some point should be refactored. Right now, we are focused on fixes to the Svelvet npm package but once we're a bit more confident that the package is stable we'll be looking to improve the site.

Leaving ticket open for now

**Comment by andrew-widjaja** [comment]
Oh for sure, actual package updates/fixes take priority :) just adding to the backlog for future contributors to consider

**Comment by mikemklee** [comment]
+1 on this, would love to have a documentation site for the actual API

e.g.,

What props are supported for `<Svelvet />` etc.

**Comment by briangregoryholmes** [comment]
Closing this issue as our documentation has been completely revamped for Svelvet 7. I'm sure there will be new issues that crop up, but I believe this one related to organization has been addressed.

Thanks for your contribution.
