### ISSUE TITLE
Setting "locked" to true does not disable resizing nodes

### ISSUE THREAD

**Issue by kanersps** [open-source-labs/Svelvet#222]
As the title states, additionally an option to disable them seperately would be nice. As resizable nodes is really not something I want in my application for example, while moving could be.

**Comment by michael-chiang-dev5** [comment]
Sounds reasonable! We can roll this in next patch

**Comment by michael-chiang-dev5** [comment]
Hi @kanersps,

We've added in functionality to disable resizable nodes and highlighting edges in this patch (6.0.12)! 

Here is the stackblitz to show the prop you need to pass in:
https://stackblitz.com/edit/disable-resize-hover?file=package.json,src%2Froutes%2F%2Blayout.svelte

Closing ticket, but if there are any issues please do not hesitate to reopen. Thank you for supporting Svelvet!
