### ISSUE TITLE
Clicking a default edge results in an empty console log

### ISSUE THREAD

**Issue by kanersps** [open-source-labs/Svelvet#223]
![image](https://user-images.githubusercontent.com/12296463/218803638-f6dd1f65-128b-43e0-8f75-01648e9cf49c.png)

Example above

**Comment by michael-chiang-dev5** [comment]
Thank you for the bug report!

Bug is fixed in npm package svelvet@6.0.8

Closing ticket, but if you have any questions/bugs please don't hesitate to re-open. Thank you for supporting Svelvet!
