### ISSUE TITLE
Could not find a declaration file for module 'svelvet'

### ISSUE THREAD

**Issue by tommyminds** [open-source-labs/Svelvet#228]
Hi,

I am completely stuck trying to upgrade to 6.0.x when using the library in a typescript project. First I believed it had to do with the missing types folder, but I keep having the same issue with 6.0.8. The only thing that has worked for me so far is downgrade to 5.x.xn

<img width="530" alt="Screenshot 2023-02-16 at 09 55 58" src="https://user-images.githubusercontent.com/123474/219316398-ecfef842-1b06-4394-8b0d-19d2ba28b056.png">

Could not find a declaration file for module 'svelvet'. '/Users/minds/repos/helixer/universe/control/console/node_modules/svelvet/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/svelvet` if it exists or add a new declaration (.d.ts) file containing `declare module 'svelvet';`ts(7016)

Am I missing something that I have to do in order for svelvet to work in a typescript project?

If I create a file named index.d.ts inside `node_modules/svelvet`, and add the content of the index.js file, everything works as expected.

**Comment by michael-chiang-dev5** [comment]
Hi @tommyminds,

Thanks for the bug report! It sounds like the index.d.ts file fixes things so we can do that in the next patch.

I was wondering if you have a specific repo that demonstrates the bug? We can't replicate it on our end and we want to make sure the fix solves your issue. If you don't have a repo readily avaiable / can't share it 100% okay, the fix you posted is specific and we can roll it out and hope for the best :) 

Thank you for supporting Svelvet!

**Comment by michael-chiang-dev5** [comment]
Hi @tommyminds,

We now generate a declaration file index.d.ts in the latest patch 6.0.9. Based on your proposed fix (thanks for that!) this should fix your issue.

Closing ticket, but if there are remaining issues (or if you have a repo so we can replicate the bug) please do not hestitate to message or reopen. Thank you for supporting Svelvet!
