### ISSUE TITLE
2 way data binding for nodes and edges

### ISSUE THREAD

**Issue by wighawag** [open-source-labs/Svelvet#229]
It seems that if I do
```
<script>
	import Svelvet from "svelvet";

	let myNodes = [
	  {
	    id: 1,
	    position: { x: 50, y: 50 },
	    data: { label: "Input Node" },
	    width: 175,
	    height: 40,
	    bgColor: "white"
	  },
	  {
	    id: 2,
	    position: { x: 100, y: 150 },
	    data: { label: "Default Node" },
	    width: 175,
	    height: 40,
	    bgColor: "white"
	  },
	  {
	    id: 3,
	    position: { x: 150, y: 250 },
	    data: { label: "Output Node" },
	    width: 175,
	    height: 40,
	    bgColor: "white"
	  }
	];

	let myEdges = [
	  { id: "e1-2", source: 1, target: 2, label: "edge label" },
	  { id: "e2-3", source: 2, target: 3 }
	];
</script>

</script>

<Svelvet bind:nodes={myNodes} bind:edges={myEdges} editable=true />

<p>Label of the first node: {myNodes[0].data.label}</p>

```

I do not get 2 way data binding works. The update I do in the graph by for example changing the name of the first node is not reflected in myNodes / myEdges

**Comment by michael-chiang-dev5** [comment]
Hi @wighawag 

Two-way binding is not implemented in Svelvet (currently) although that is obviously something we want to do

We do not have an ETA for this feature (currently focused on fixing bugs, tests, and documentation) but will leave this issue open until it is resolved!

**Comment by rohanrajpal** [comment]
Are any workarounds possible yet? Maybe we can use the shareable feature to somehow get the current state of diagram without downloading?

**Comment by crcdng** [comment]
+1 if this could be highly prioritised somehow, IMHO the ui being updated from the model is *the* essential feature for a library based on a reactive framework.

**Comment by briangregoryholmes** [comment]
In Svelvet 7, we recommend handling reactivity on your custom nodes directly (you can pass children to our Node component), but we've also introduced exactly what you've asked for here on default nodes. See video below for an example implementation.


https://user-images.githubusercontent.com/120223836/231313140-54fabfd3-4ce1-4edc-851e-a9b71aead038.mov

**Comment by briangregoryholmes** [comment]
Closing as the general functionality has been added in Svelvet 7. Please start new issues if you notice anything off about the existing implementation.

Thank you!

**Comment by Akash-Sharma-1** [comment]
Hi @briangregoryholmes ,

Thank you so much for the example :) 

Just a small question , I wanted to add the "new node" such that it is positioned at the center of the view port when added. 

In the previous version of Svelvet -> we could use the 'canvas id' to get to the center of the visible view as explained here - https://stackoverflow.com/questions/21486182/d3-force-layout-finding-relative-center-based-on-current-visible-view/55853114#55853114

How can we perform the same in Svelvet 7?

**Comment by briangregoryholmes** [comment]
@Akash-Sharma-1

Hi, Akash. I've just pushed a new version, 7.0.24 with the following features.

There is now a prop on the Node component called `center`. Who true, the initial position of the Node will be set to the optical center of the viewport.

There is a derived value on the graph object also called center. Like before, the graph object can be accessed by any component in the context of Svelvet via getContext('graph').

There is a function exposed at the package level called `getViewportCenter`. It takes a string form of the graph id.

Let me know how these end up working for you.
