### ISSUE TITLE
Use of eval in is strongly discouraged as it poses security risks

### ISSUE THREAD

**Issue by YugoCode** [open-source-labs/Svelvet#230]
Just noticed following two warning messages when running tests with Playwright:

- Use of eval in "node_modules/svelvet/importingExporting/views/ImportExport.svelte" is strongly discouraged as it poses security risks and may cause issues with minification.
- "local" is imported from external module "d3-selection" but never used in "node_modules/svelvet/container/views/GraphView.svelte".

**Comment by michael-chiang-dev5** [comment]
Hi @YugoCode,

Thanks for the heads up!

- the `eval` in the ImportExport feature is a known issue. This feature was implemented by a previous team, and eval is used to handle custom svelte components in nodes.
-  The unused import is easier to fix and we can roll that in next patch 

Thank you for supporting Svelvet!

Leaving this ticket open for future maintainers because removing `eval` warrants discussion. There are 3 options
* Leave `eval` in as is
* Remove `eval` and disable custom svelte components when using the import/export feature
* Remove the import/export feature entirely; this feature will become more and more difficult to maintain as additional features are added. It is already unable to handle callbacks.

**Comment by zacharygriffee** [comment]
I remember looking through svelte 4 code when I first started working with it, and I immediately spotted this vulnerability myself and removed it from my project. I personally maintain the state of the nodes through other ways; and most of the nodes I'm using are custom svelte components that handle their own state. So I'd personally vote for 3; remove import/export feature and drop the eval before it's too late.

**Comment by jycouet** [comment]
What about `opt-in` / `opt-out` this feature using `eval`? 
Something like: 
```
<Svelvet
  usingEval=(true|false)
 />
 ```
 
 And `true` by default will not make any breaking changes.
 Like this, it will be treeshacked out?

**Comment by briangregoryholmes** [comment]
The use of eval has been removed in Svelvet 7. Thank you for bringing this to our attention.

**Comment by jycouet** [comment]
Do you know when version 7 will be published on npm?

**Comment by briangregoryholmes** [comment]
Should be late this evening with an announcement tomorrow morning.

**Comment by jycouet** [comment]
Exciting 🎉 🎉 🎉

**Comment by briangregoryholmes** [comment]
@jycouet It's live now! Here's a link to our new docs and sandbox: https://svelvet.mintlify.app/introduction

We're working on getting the website itself updated and should have a full announcement soon

**Comment by jycouet** [comment]
I'm trying the upgrade. Do you have a guide like "how to go from 6 to 7"?
In changelog, I don't see any breaking changes.

```ts
<script lang="ts">
  import Svelvet, { type UserNodeType } from 'svelvet'

  function getNodes(){
  
    // some logic...
  
    return {
      nodes: [ ... ],
      edges: [ ... ]
    }
  }
  
  function node(n){
  
   // more code...
  
    return {
      id,
      position: {
        x: col * box.width + (box.width - width) / 2,
	y: line * box.height + (box.height - height) / 2
      },
      data: { label: label ?? '' },
      width,
      height,
      borderRadius: type === 'label' ? 100 : 0,
      sourcePosition: 'bottom',
      targetPosition: 'top',
      bgColor: bgColor === 'white'
	  ? 'white'
	  : bgColor === 'green'
	  ? green
	  : bgColor === 'orange'
	  ? orange
	  : bgColor === 'transparent'
	  ? 'transparent'
	  : red,
	clickCallback: (node) => {
	if (node.id !== 'REF') {
	  showEDIT_Rule = true
	  EDIT_RuleId = node.id
        } else {
	  showEDIT_Rule = false
	  EDIT_RuleId = null
	}
      }
    } as unknown as UserNodeType
  }

</script>

{@const data = getNodes()}
<Svelvet
  nodes={data.nodes.map((c) => node(c))}
  edges={data.edges}
  width={1200}
  height={1000}
  bgColor="transparent"
  initialZoom={1}
  initialLocation={data.nodes[0].position}
  minimap={true}
/>
```

But, I had various issues using `7`:
- no more export default. Ok `import { Svelvet } from 'svelvet'` seems to work
- no more `type UserNodeType`. 

Could you guide me? Should I open a dedicated issue? We can chat on discord if it's easier :)

**Comment by briangregoryholmes** [comment]
Hey, JYC. For more general questions about the new API, I think the best place to get started would be our new documentation (https://svelvet.mintlify.app) and our article covering the release: https://medium.com/@jenlee_35516/svelvet-7-0-build-intuitive-interactive-node-diagrams-in-svelte-cb4e78872ff. The documentation features extensive prop definitions for all our new components.

That said, I'm gonna work on a specific section about upgrading. Thanks for bringing this to our attention.

Feel free to contact me on Discord with any questions you have! I'm burg#5391

I recommend checking out the StackBlitz sandbox in the documentation. It features the graph now shown on our landing page and is an example of a more complex project. 

For your particular code linked above, here are the changes:

There is no longer a nodes prop on the Svelvet component. There is a Node component itself that takes props and should be passed as a child of Svelvet. You can iterate and conditionally render Nodes using all the standard Svelte syntax. You would just spread each element of your object over the Node component like this if you were trying to emulate Svelvet 6 functionality.

```html
<script>
import { Node, Svelvet} from 'svelvet'
import type { NodeConfig } from 'svelvet'

</script>
  {#each data.nodes as node}
      <Node {...node} />
  {/each}
  ```
  
The equivalent to UserNodeType is NodeConfig.

Width and height are passed as part of a dimensions object {width: number, height: number}. Default is 200x100
  
 The prop controlling initial zoom is now called zoom as it features two way data binding and can be updated dynamically. It's no longer just the initial zoom!
  
 Initial location has not been re-added as a prop, but there is a new prop called fitView that should do what you're looking for. We'll re-add initialLocation for users still want it. You can pass fitView="resize" to have Svelvet automatically recalculate fitView on viewport resize events.
  
 Target position and source position are no longer part of a NodeConfig/UserNodeType. You can specify Node direction by passing "TD" or "LR", which would place input anchors on the top/bottom or left/right respectively. You can specify an arbitrary number of Anchors with the inputs/outputs props. For the greatest level of customization, we suggest creating custom Node, which is Svelvet 7's primary focus. You can wrap our Node component around whatever HTML elements you want and can place any number of our Anchor components anywhere within those elements and we'll track and handle connection logic behind the scenes.
  
 Click callbacks are also no longer part of the NodeConfig/UserNodeType. There is an event on the Node component you can listen for called on:nodeClicked. We pass the entire Node object as part of the event, but it's also accessible via let:node. There's also on:connection and on:disconnection for firing events when the state of an Anchor changes.
  
  ```html
<script>
import { Node, Svelvet} from 'svelvet'
import type { NodeConfig } from 'svelvet'
import CustomNode from './CustomNode.svelte'

function myFunction(e: CustomEvent) {
    console.log(e)
}
</script>

<Svelvet>
  <Node on:nodeClicked={myFunction} />
  <CustomNode/>
</Svelvet>
  ```
  
  Finally, for setting the grid color to "transparent" you would import the Background component, configure its props (bgColor, dotColor, gridSize, etc.) and pass it via the background slot. If you're just looking to more generally style everything at once, Svelvet now takes a theme prop with a few default styles like light and dark. We'll be adding more soon and allowing developers to pass their own global theme as well.
  
  ```html
  
  <script lang="ts">
	import { Svelvet, Node, Background } from 'svelvet';
</script>

<Svelvet width={800} height={600} minimap>
	<Node />
	<Background slot="background" bgColor="transparent" />
</Svelvet>
```

**Comment by jycouet** [comment]
Wow, thx a lot @briangregoryholmes for this long and detailed post.

I have to say that I was worried a bit with my first attempt of upgrading without all these information. Now, I'm way more confident, and I see the `svelte` DX style. Love it.

Side note, You might want to update the medium link, as this one is going to a 404.
I managed to find it https://medium.com/@jenlee_35516/svelvet-7-0-build-intuitive-interactive-node-diagrams-in-svelte-cb4e78872ff6

Thx again.
I will speak to you on Discord. 👍

**Comment by briangregoryholmes** [comment]
Thanks for pointing out the issue with the article link. Fixed. Please continue to push on anything that seems off or needs clarification and we will adjust accordingly.

Here's a link to some more thoughts on the motivation behind the changes: https://github.com/open-source-labs/Svelvet/issues/250#issuecomment-1518071086
