### ISSUE TITLE
🐞 Bug: Cannot start a react app with Svelvet imported

### ISSUE THREAD

**Issue by marshal0224** [open-source-labs/Svelvet#233]
---
🐞 Bug: Cannot start a react app with Svelvet imported
---

### Current Behavior:

A freshly created react app throws an error with Svelvet imported (even without any usage). 

### Expected Behavior:

Svelvet does not break the app.

### Steps To Reproduce:

1. Create a new react app with create-react-app
2. npm i svelvet
3. add "import Svelvet from 'svelvet'" to app.js
4. See the following error:
```
ERROR in ./node_modules/svelvet/index.js 5:0-30
Module not found: Error: Can't resolve './types/types' in '\node_modules\svelvet'
Did you mean 'types.js'?
BREAKING CHANGE: The request './types/types' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 1 error and 1 warning
```
### Environment:
- OS: Windows 10
- Node: 16.13.2
- npm: 8.1.2
- "react": "^18.2.0",
- "react-dom": "^18.2.0",
- "react-scripts": "5.0.1",
- "svelvet": "^6.0.9",

**Comment by marshal0224** [comment]
p.s. I tried to edit the source files in ./types by adding the extensions to the scripts, but that also did not work out. Even if it were to work, it would be a temporary fix, but if anyone could point out why this temporary fix does not work, that would also be great and appreciated!

**Comment by TensionCoding** [comment]
Hey @marshal0224, Svelvet was developed for the Svelte compiler. If you would like to use a similar library for React, check out {React Flow](https://reactflow.dev/).

**Comment by marshal0224** [comment]
> Hey @marshal0224, Svelvet was developed for the Svelte compiler. If you would like to use a similar library for React, check out [React Flow](https://reactflow.dev/).

Thanks for the swift reply. I will try React Flow instead, then.
