### ISSUE TITLE
FR ✨: Editable/Customizable anchors

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#236]
Currently it is possible to customize the anchor position using callbacks mentioned in the docs below

https://www.svelvet.io/docs/CustomAnchorPosition/

However, they are not editable

![image](https://user-images.githubusercontent.com/7023147/220317039-3a02b2d1-8915-4a10-a363-85a3dabb6914.png)

Good things is that this is possible in other libraries & we can learn from it, In order to build something like below:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/7023147/220314826-727065d0-d562-4d82-a7ab-265a272949fa.png">

We would need a concept like `<Handle>` is in react flow, so that in a custom node one can specify from where the handle would be, if its a target or a source. That way even after one has exported the diagram, we can know from which anchor the edge started & where it ended rather than the information getting lost in callbacks 

react flow docs for inspiration:
https://reactflow.dev/docs/examples/overview/
https://reactflow.dev/docs/api/nodes/handle/

**Comment by rohanrajpal** [comment]
I've been trying to understand on how this can be achieved in the next version.

From what I've been able to understand, there are two types of anchors

```ts
// src/lib/store/types/types.ts
export interface PotentialAnchorType {
  id: string;
  nodeId: string;
  callback: Function; // callback is used to calculate positionX, positionY based on parent node's data, and set the anchor position // TODO: rename to something better
  positionX: number;
  positionY: number;
  angle: number;
  canvasId: string;
  delete: Function;
}

// src/lib/edges/types/types.ts
export interface AnchorType {
  id: string; // note that the user never specifies an anchor and they are generated dynamically. id will be a random string.
  nodeId: string;
  edgeId: string;
  sourceOrTarget: "source" | "target";
  positionX: number;
  positionY: number;
  callback: AnchorCbType; // callback is used to calculate positionX, positionY based on parent node's data, and set the anchor position // TODO: rename to something better
  angle: number;
  setPositionFromNode: Function;
  setPosition: Function;
  updateEdges: Function;
  getOtherAnchorId: Function;
}
```

**Comment by michael-chiang-dev5** [comment]
Hi Rohit,

This is definitely achievable in the next version. For each node, the user could pass in an array of callbacks, where each callback defines the position of a potentialAnchor.

Right now the team is trying to get documentation and testing in a better state, but once that is done we can look to implement new features and this is certainly at the top of the list!

**Comment by rohanrajpal** [comment]
That's amazing! Also it'd be great if we can add a css class for each anchor as well since controlling the look and feel of an anchor would be quite important for such use cases. 

Also another idea is to have a `CustomAnchor` component that one can use in the custom node which automatically creates the Potential anchor at the required position. I'll share a sample implementation soon :)

**Comment by rohanrajpal** [comment]
Also i guess #174 would be quite important to implement before this is done. You can check how svelte-headless-table is rendering custom components in a typesafe way, it's a great solution to pass in props and also take advantage of typescript.

**Comment by rohanrajpal** [comment]
Sorry for the late reply, here is how i've figured it out so far

We create a CustomAnchor.svelte component

```svelte
<script lang="ts">
  import { rightCb } from "$lib/edges/controllers/anchorCbUser";
  import { findStore } from "$lib/store/controllers/storeApi";
  import { createPotentialAnchor } from "$lib/store/controllers/util";

  // get the required args to create an anchor
  export let id: string,
    positionCb: Function = rightCb,
    canvasId = "workflow",
    nodeId: string;

  const store = findStore(canvasId);

  // create if not already made using the anchor store
  const newAnchor = createPotentialAnchor(
    positionCb,
    store,
    nodeId,
    canvasId,
    id
  );

  store.potentialAnchorsStore.update((anchor) => {
    anchor[newAnchor.id] = newAnchor;
    return anchor;
  });

  newAnchor.callback();
  // allow customizing the anchor accordingly
</script>
```

and then use it in a custom node like

```
<script>
  import CustomAnchor from "$lib/edges/views/Edges/CustomAnchor.svelte";

  export let nodeId = "7";
  const middleAnchor = (xNode, yNode, widthNode, heightNode) => {
    const xAnchor = xNode + widthNode;
    const yAnchor = yNode + heightNode / 2;
    return [xAnchor, yAnchor, 0];
  };
  const bottomAnchor = (xNode, yNode, widthNode, heightNode) => {
    const xAnchor = xNode + widthNode;
    const yAnchor = yNode + (5 * heightNode) / 6;
    return [xAnchor, yAnchor, 0];
  };
</script>

<div class="relative">
  <p class="">This is a custom node 7</p>

  <CustomAnchor id="anchor-69" {nodeId} positionCb={middleAnchor} />

  <CustomAnchor id="anchor-619" {nodeId} positionCb={bottomAnchor} />
</div>

<style>
   /* Also maybe we can allow passing a class to a custom anchor to style it as we want */
</style>
```

this gives us the most flexibility, the callbacks are still necessary as they provide further flexibility in the direction of the anchor & class gives the flexibility for the appearance of the anchor

**Comment by rohanrajpal** [comment]
> Also i guess #174 would be quite important to implement before this is done. You can check how svelte-headless-table is rendering custom components in a typesafe way, it's a great solution to pass in props and also take advantage of typescript.

Update: headless-table uses svelte render to achieve this, we can use it directly in svelvet: https://github.com/bryanmylee/svelte-render

**Comment by briangregoryholmes** [comment]
Closing as this functionality was added in Svelvet 7. Issues related to the new functionality should be created in their own threads.

Thanks for your contributions!
