### ISSUE TITLE
Is there a way to opt out of dynamic anchors?

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#238]
Hey, Dynamic anchors is great feature and makes diagrams much much easier!

https://www.svelvet.io/docs/DynamicAnchor/

But is there a way to opt out of it? My use case in the image below requires the anchor to be a at a specific place which i'm achieving via custom anchors.

![image](https://user-images.githubusercontent.com/7023147/220549509-da34f061-4f14-41cb-a9dd-53c2bec770e6.png)

**Comment by michael-chiang-dev5** [comment]
Hi,

If you specify custom anchors, they should not be dynamic. See the stackblitz here: https://stackblitz.com/edit/custom-anchors?file=src/routes/+layout.svelte
Notice how you can set two custom anchors for the top node? If you don't set the custom anchor, it defaults to a dynamic anchor

Thank you for supporting svelvet! If closing ticket but if you have any questions feel free to re-open it
