### ISSUE TITLE
FR: Support for grouping and nesting

### ISSUE THREAD

**Issue by tmarsik42** [open-source-labs/Svelvet#240]
It's amazing we can group nodes now but is it possible to group them visually (draw border around a group of nodes) and nest them?

My use case is I have a node inside node inside node etc and edges can go from whatever level of node to wherever.

edit: something like reactflow (https://reactflow.dev/docs/examples/layout/sub-flows/)

**Comment by briangregoryholmes** [comment]
Version 7 will have this feature. Perhaps not as robust as Rdact Flow to begin with, but nodes will respect the boundaries of their group boxes and there will be a visual representation of the bounding box that you can use to move all the nodes at once. You can create these via shift+cmd+click and drag or by specifying them ahead of time.
