### ISSUE TITLE
Feature: passing params to a custom Svelte element

### ISSUE THREAD

**Issue by bitprofve** [open-source-labs/Svelvet#248]
It would be helpful to pass params to a custom Svelte element.

Example, for the following scenario:
node.data = { custom: Diagnose }

it would be nice to pass an object as params, for example like this:
node.data = { custom: Diagnose, params: {a="b", c="3"} }

**Comment by rohanrajpal** [comment]
Duplicate #174

**Comment by briangregoryholmes** [comment]
An equivalent feature has been enabled in Svelvet 7.

Thank you for your contribution!
