### ISSUE TITLE
[FEATURE] Fit-in-View

### ISSUE THREAD

**Issue by Cahllagerfeld** [open-source-labs/Svelvet#249]
Adding a prop or an option to the svelvet instance to fit all nodes in the viewport. Similar to [react-flows feature](https://reactflow.dev/docs/api/react-flow-props/#fitview)

**Comment by briangregoryholmes** [comment]
Will add very soon

**Comment by briangregoryholmes** [comment]
Added in version 7.0.4. You can pass the fitView prop to Svelvet to calculate it onMount and what was previously a "reset" button in the Controls component is now a "fitView" button. We'll add customization options to this behavior with time

Thanks for your contribution!

**Comment by rudolfbyker** [comment]
Is there a way to call `fitView` programmatically, without adding `Controls`?
