### ISSUE TITLE
How to incorporate edge click events?

### ISSUE THREAD

**Issue by msze400** [open-source-labs/Svelvet#250]
I want to add click events to our edges. As shown in v6.0 https://medium.com/@hor.val/svelvet-6-0-the-svelte-component-library-for-building-interactive-node-based-diagrams-81dafa2d50cd.

Is there an example of how this is done anywhere in the docs? I don't see the property anywhere listed on this page
https://www.svelvet.io/docs/custom-edges/

**Comment by briangregoryholmes** [comment]
Hey, Matt. The process of creating Edges has changed in Svelvet 7, so we'd love some feedback on how we've changed the way edge click events work.

Edges are created as components that can be passed to the Svelvet, Node or Anchor components. In an edge component, you can either customize it via props or pass an HTML path element/label as children. In the second scenario, developers could easily add edge click events to the path themselves using standard Svelte syntax, which may offer improved flexibility and control, though you would have to manually set pointer events on the path using CSS. However, our Edge component also accept an edgeClick and targetColor that can be used as seen below:

```js
<script lang="ts">
	import Edge from '$lib/components/Edge/Edge.svelte';
	import { getRandomColor } from '$lib/utils';
	import type { CSSColorString } from '$lib/types';

	let color: CSSColorString = 'yellow';

	function randomColor() {
		color = getRandomColor();
	}
</script>

<Edge let:path edgeClick={randomColor} targetColor={'blue'}>
	<path style:stroke={color} d={path} />
	<div slot="label">Custom Label</div>
</Edge>

<style>
	div {
		width: fit-content;
		height: 2rem;
		display: flex;
		justify-content: center;
		align-items: center;
		background-color: rgb(229, 10, 10);
	}
	path {
		stroke-width: 4px;
	}
</style>
```

**Comment by msze400** [comment]
Hi Brian, 

Thanks for updating this, glad the Svelvet team is still innovating. 

Curious though what was the reason for the rewrite for how nodes and edges are generated? Our team is trying to weigh the cost and benefits of picking up the new v7 upgrade because it looks like it would require a pretty large lift in order to get our node and edge structure to fit the new configuration.

**Comment by briangregoryholmes** [comment]
So, in broad terms, the reason for the rewrite was to add additional flexibility, customization and control. I realize those terms are sort of nebulous, but, in general, we were running into a lot of feature requests that were not possible with the previous approach, especially around two way data binding and custom Nodes. We think the change makes creating dynamic graphs more intuitive and significantly less verbose. I would be more than happy to take the time to deep dive on your particular use case. We are really dedicated to making this a powerful and intuitive tool and want to ensure the needs of the community are met and exceeded!

I think the sandbox here gives a good example of what's possible with this new approach and how the code structure has been improved: https://svelvet.mintlify.app/introduction

To us, there are four important concepts:

Nodes: These are dynamic, modular, reusable components. You should be able to take any Svelte component, wrap it in our Node component and turn it into a draggable, connectable element with the ability to apply conditional styles based on state. Enabling this required rethinking graph composition and Node creation. We couldn't simply added additional entries to Svelvet's UserNodeType. We wanted to leverage the approaches from JavaScript and CSS that developers are already familiar with, especially those that are unique to Svelte.

Anchors: Anchors are not simply visual representations of a point on a Node. They have their own internal logic and state. They can be inputs, outputs, connected, connecting, etc. They can also have directionality based on whether they're positioned. You should also be able to place them on a Node using standard CSS. Again, we found ourselves wanting an Anchor component that we could customize and place in an intuitive manner.

Edges: An Edge is also just a component. It should be modular, reusable and dynamic and decoupled from the idea of a connection. Again, we found ourselves wanting an Edge component that we could style arbitrarily and pass around to the various Nodes and Anchors that should use it. Creating Edges as these kind of repetitive, rigid data structures simply didn't allow this.

Connections: Connections are just a piece of state saying that two anchors are connected to each other. This idea is unrelated to the idea of an Edge and should be as decoupled as possible. Connections should also allow for specification at various levels of granularity. Sometimes I want to just broadly say that one Node is connected to another and let Svelvet choose which Anchors are visually connected. Other times, I want to specify exact Anchors. More importantly, we wanted our connection state intimately tied to the Nodes and Anchors involved. You should not have to look through a dense array of Edge objects to quickly see what it's connected to.

Additionally, we wanted to give users the ability to compose Nodes as singular objects/components and then add them to a graph in the same way you would structure any component tree. We think this feels really intuitive for React/Svelte developers. It also enables all the standard Svelte syntax for iteration and conditional rendering. 

```HTML
<Svelvet>
   <Group>
        <Node/>
        <Node/>
        <Node/>
    </Group>
   <CustomNode/>
</Svelvet>
````
This is a simplification, of course. But I think it shows the value in this new way of thinking. You have an immediate visual representation of the hierarchy/structure of graphs with this new API.

When creating custom Nodes, you can do so in the context of what Svelvet provides. Wrapping your HTML elements in <Node/> means you have access to the on:nodeClicked, let:grabHandle, on:connection and on:disconnection functionality to completely control the state of your Node. This kind of flexibility just wasn't possible with the array of objects approach.

Here's a really simple custom Node:

```HTML
<script lang="ts">
	import { Node, Anchor } from 'svelvet';
</script>

<Node let:selected >
	<div class="node" class:selected>
		<div class="input-anchors">
			<Anchor
				on:disconnection={() => console.log('disconnection')}
				on:connection={() => console.log('connection')}
				input
			/>
		</div>
		<div class="output-anchors">
			<Anchor output />
		</div>
	</div>
</Node>

<style>
	.node {
		box-sizing: border-box;
		width: 100%;
		height: 100%;
		background-color: rgba(128, 128, 128, 0.673);
		border-radius: 20px;
		position: relative;
		height: fit-content;
		display: flex;
		flex-direction: column;
		padding: 10px;
		border: solid 2px rgb(99, 99, 99);
	}

	.selected {
		border: solid 2px white;
	}
	.input-anchors {
		position: absolute;
		display: flex;
		flex-direction: column;
		gap: 10px;
		top: -20px;
	}

	.output-anchors {
		position: absolute;
		right: 20px;
		bottom: 20px;
		display: flex;
		flex-direction: column;
		gap: 10px;
	}
</style>
```
I think this results in something that Svelte/React developer can really quickly wrap their heads around. We have conditional styling based on whether the Node is selected and a really familiar way of placing Anchors that feels like any other component library. There's so much more you can do now, like pass custom elements to the Anchor component or listen for click events on the Node component, but this is just an illustration to get the point across

Our change to Edges was really driven by user feedback. One, it was difficult to specify an Edge "type" without also specifying an Edge connection. Now, the two ideas are decoupled. Edges and connections are separate concepts. You can create an arbitrary number of custom Edges (that allow for total customization) and pass them in any kind of composition to Node, Svelvet or Anchor. Structuring them as components means we can pass additional functionality, like the ability to remove an Edge via let:destroy and have developers totally control when and how those methods are called.

Like I said at the top, I would love to spend more time discussing this with you and your team. You can contact me on Discord burg#5391 or via email briangregoryholmes@gmail.com. We want Svelvet to be a flexible and powerful tool, with features directed by user feedback. Figuring out how we can make Svelvet better for your use case would, I'm sure, result in improvements for all users.
