### ISSUE TITLE
Setting width/height with non-number values?

### ISSUE THREAD

**Issue by mikemklee** [open-source-labs/Svelvet#252]
the `width` and `height` props for `<Svelvet />` seem to only support numbers, like pixel values for example.

Is it possible to set other non-number values that are still valid for width and height, such as `100%` or `auto`?

Also, is there a place in the documentation where one can learn more about the different props, their types, and their usage examples?

**Comment by rohanrajpal** [comment]
+1, right now i use the <svelte:window> to calculate the width and assign it accordingly

**Comment by briangregoryholmes** [comment]
Let us know if the new functionality in Svelvet 7, which is live now, achieves what you're looking for. If you don't pass a width and height parameter to the Svelvet component, it will fill the wrapping container.

**Comment by rohanrajpal** [comment]
This is working now, thanks!
