### ISSUE TITLE
[Website - Bug] No option to submit new issues for the Svelvet website

### ISSUE THREAD

**Issue by mikemklee** [open-source-labs/Svelvet#253]
![image](https://user-images.githubusercontent.com/17537040/232231633-1fecdb91-aa76-4b53-b3d1-368f626fe642.png)

The `Svelvet-website` repo does not have an `issues` tab, so there is no way to submit issues.

**Comment by briangregoryholmes** [comment]
Changed repo to allow for issues and discussions.

Thanks, Mike!
