### ISSUE TITLE
`on:connection` not getting fired for `Anchor`

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#261]
Loved the 7.0 update team! Really appreciate the time and efforts spent on this library.

If i try to log the `on:connection` event, then nothing gets logged, but `on:disconnection` workds correctly. 

Use case: I'll be using these events to maintain a store of all the connections in my graph, so that i can store it in a db & later reconstruct it when a user logs in later.

```svelte
<Anchor
    id={key}
    let:hovering
    let:connecting
    let:linked
    on:connection={(e) => {
      console.log(e); // not getting fired
    }}
    on:disconnection={(e) => {
      console.log(e); // working as expected
    }}
    inputsStore={inputs}
    {key}
    input
  >
 ```

**Comment by rohanrajpal** [comment]
To reproduce, I took the stackblitz provided in the docs, and added the console.log like above

**Comment by rohanrajpal** [comment]
Another find, if an anchor is already connected to another anchor, and i connect one more, then this event is fired. I guess its a small logic mistake.

**Comment by briangregoryholmes** [comment]
Ah, the classic 0 is falsy issue! We just weren't updating the previousConnectionCount correctly when it dropped to zero. Should be fixed in the latest version. Let me know. Also added a Playwright test to check this functionality.

Thanks, Rohan!

**Comment by rohanrajpal** [comment]
> Ah, the classic 0 is falsy issue! We just weren't updating the previousConnectionCount correctly when it dropped to zero. Should be fixed in the latest version. Let me know. Also added a Playwright test to check this functionality.
> 
> Thanks, Rohan!

Hahah indeed the falsy issue, glad we have test to protect this now!
