### ISSUE TITLE
Types of `createStore` not exported correctly

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#264]
I was trying to export the graph using this method

```ts
const graph = getContext<Graph>('graph');
	const nodes = graph.nodes; // strangely, type is coming out as any?
	const edges = graph.edges;

	function exportNodes() {
		for (const [key, node] of Object.entries($nodes)) {
			console.log(node.id, get(node.position), get(node.nodeLevelConnections), node.anchors);
		}
	}

	$: if ($nodes && $edges) exportNodes();
```

on futher investigation, it looks like the `.d.ts` file of `createStore` is missing form the build? Not sure why, looks like its correctly exported in the source code.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/7023147/233444923-51762d64-aaca-40ea-a036-a65bc4855fcb.png">

![image](https://user-images.githubusercontent.com/7023147/233445373-9a234d2e-f71a-48fd-86d7-4f8f878fc651.png)

**Comment by rohanrajpal** [comment]
Understood the issue, the `createStore` function does not have an explicit export, I guess giving that should fix it

https://github.com/open-source-labs/Svelvet/blob/main/src/lib/utils/creators/createStore.ts#L4

**Comment by briangregoryholmes** [comment]
Looking into it.

**Comment by rohanrajpal** [comment]
Figured it out, making a PR (not sure if its the best solution tho)
