### ISSUE TITLE
Programmatic `Node` & `Edge` deletion?

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#268]
Hey, how does one go about programmatically deleting a node or edge? We were thinking of adding a cross button to our nodes & edge.

I guess there might be a way with using the `graph` store, but not sure.

**Comment by briangregoryholmes** [comment]
Hey, Rohan. There's a let:destroy function on the Edge component that you can call. For instance, via an on:click event placed on a label.

I'm adding one for Nodes now, but, in the meantime, you can achieve this pretty easily via the following:

```HTML
<script lang="ts">
	import { Node, Anchor } from 'svelvet';

	import { getContext } from 'svelte';

	const graph = getContext('graph');
</script>
<Node let:node let:selected>
	<div>
		<button on:click={() => graph.nodes.delete(node.id)}>Delete Node</button>
		<Anchor />
	</div>
</Node>
```
Edges are automatically deleted when their corresponding Anchor components are unmounted, so this should cascade appropriately.

**Comment by briangregoryholmes** [comment]
Okay. I just added it. Access it via let:destroy on the Node component. You could reimplement the above via `on:click={destroy}`

**Comment by rohanrajpal** [comment]
Awesome!
