### ISSUE TITLE
Unable to animate edges and set color per anchor

### ISSUE THREAD

**Issue by eliasdefaria** [open-source-labs/Svelvet#280]
Hello there, I have a use case where I'd like to set a global `Edge` custom component so that I can set the animate property to true on all edges. Within certain anchors, I would then like to set the color dynamically based on data in a Svelte store. This kind of case would be simple if I were able to pass props to the custom defined edge component, or rather access the edge being rendered within the `<Edge` definition like so:

```
<Edge animate let:edge>
    {...}
</Edge>
```

Is there currently a way to do this currently that I'm missing? Another easy solution might just be to allow users to set an `edgeAnimation` property on `Anchor` and `Svelvet` elements.

Thanks!

**Comment by briangregoryholmes** [comment]
Hey, Elias, so this is actually possible at the moment. I'm not sure if I would call it a workaround, but we have some plans to make this a lot more intuitive.

The edgeColor prop on an Anchor accepts a Writable<CSS Color String>. So, what you would do is create your Edge component with whatever kind of props you want and, as long as you don't set a color prop, the edge will inherit the store value of the source anchor. This was kind of an attempt to get edges to the exist within the contextual space of the Anchors and Nodes that create them, but it's an imperfect implementation.

Let me throw together a quick sandbox.

**Comment by briangregoryholmes** [comment]
Here you go: https://stackblitz.com/edit/vitejs-vite-r7zd9p?file=src/lib/CustomNode.svelte

**Comment by eliasdefaria** [comment]
Oh awesome! Thank you so much for the quick response. I thought I had tried something like this, but where I think I went wrong was in attaching the `edge` parameter to `<Svelvet>` component as opposed to the same `<Anchor>` component I was setting the `edgeColor` on.

I can confirm it just worked though. Thank you!

**Comment by briangregoryholmes** [comment]
That should work too, actually. You can pass the Custom Edge to Svelvet and overwrite the color at the Anchor level. It's possible our docs misled you because I'm noticing it says the edgeColor prop on Anchor is just a standard CSS Color String rather than a writable.
