### ISSUE TITLE
Edge drop callback to create new nodes

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#284]
Hey, we were implementing a way for users to create a new node, something like below
<img width="917" alt="image" src="https://user-images.githubusercontent.com/7023147/234279437-b1013de6-e20a-45fd-b145-25f636fd488c.png">

I guess one essential thing would the be edge drop callback which should return the x & y of the of point when the mouse was dropped.

I saw this in the roadmap, but was just curious to know if this is planned to be introduced soon?
https://svelvet.mintlify.app/roadmap#edge-drop-callback

Thanks in advance!

**Comment by briangregoryholmes** [comment]
Working on this now.

**Comment by briangregoryholmes** [comment]
This will be in v7.0.26 released later today. It fires only when a connection is started and not completed successfully. It does not fire when disconnecting an existing edge.

**Comment by briangregoryholmes** [comment]
Live now. Please start a new issue for anything related to the implementation.

**Comment by rohanrajpal** [comment]
> Live now. Please start a new issue for anything related to the implementation.

Wow! Your speed is 🏎️
