### ISSUE TITLE
Extra information for edgeDrop evenet (x & y of the dropped position)

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#288]
Hey, thanks a lot fo working on enabling an edgedrop event, but i guess the following information would be helpful

After the edgeDrop event, i plan to open a context menu like below and when a user confirms which kind of node to add, add a node there.
![image](https://user-images.githubusercontent.com/7023147/234485324-bbd93851-4b8b-4e85-ba49-9a065f52d716.png)

To enable this use case, it'd be great if we can get the x & y position of the place where the edge was dropped. After getting this x & y coordinate, I plan to.

1. open a context menu on those coordinates
2. create a node on the same x & y position edge was dropped

**Comment by briangregoryholmes** [comment]
Added to the event detail of the edgeDrop.

```on:edgeDrop={(e) => console.log(e.detail)}```

**Comment by rohanrajpal** [comment]
Hey Brian, just realised that one last useful prop in the detail would be the nodeId & anchorId form where the edge was dropped. 

My use case is to open a modal on edge drop, allow the user to select the new node & programatically connect to that new node. So knowing from which node & anchor id the drop event came from becomes essential!
