### ISSUE TITLE
Snap to grid seems not to be functional

### ISSUE THREAD

**Issue by metrictones** [open-source-labs/Svelvet#301]
Feature is mentioned just once in the v7 docs in the Svelvet component section. Has it been removed until refactored w/ the "photoshop-esque" guides as per the roadmap? Or am I missing something ...?

Thank you for this beautiful library :)

**Comment by briangregoryholmes** [comment]
Thanks for bringing this to our attention. It should be working equivalent to the previous version while we work on the update, so I'll take a look!

**Comment by briangregoryholmes** [comment]
Found the issue. Next release will have this fixed.

**Comment by metrictones** [comment]
Thank you!

**Comment by briangregoryholmes** [comment]
Fixed in the latest version. Let me know if you have any issues.
