### ISSUE TITLE
Allow changing Z Index of edge

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#309]
If we take the following test case

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/7023147/235348599-0895d38e-e55f-47b6-981a-a9261edf2ba7.png">

It's tough to understand which anchor is connected to which node, this can be solved via two use cases

1. Control the opacity of a node, that does partly solve this problem

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/7023147/235349508-aa6c4ca7-50f0-413c-ba08-8028be9858d3.png">

2. allow changing the z index of the edge, we already have `hovering` directive to check if an edge is being hovered, but since its a path element, we cant set its z index, right? or can we? Not entirely sure on how to go about this

**Comment by rohanrajpal** [comment]
for 2. my bad, the `hovering` directive is available only for Anchor, currently this is how i'm tyring to bring the dge over the node, but i know this wont work since this is not how z-index work for svg elements.

```svelte
<style>
    #mainEdge {
        stroke: rgb(68, 68, 68);
        stroke-width: 2px;
    }

    #mainEdge:hover {
        stroke: rgb(3, 196, 226);
        cursor: pointer;
        stroke-width: 3px;
        z-index: 1000;
    }
</style>
```

**Comment by briangregoryholmes** [comment]
Adding this now. Svelvet will have two new props:

`edgesAboveNode`
`raiseEdgesOnSelect`

edgesAboveNode can be true, false or "all". This places edges either below all Nodes, above only the Nodes it's connected to or above all nodes.

raiseEdgesOnSelect can be true, "source" or "target". This raises the z-index of the edge when either node is selected or just the source/target.

I'm sure this can be more robust and I can add more fine grained control/overrides at the Node/Anchor level, but this is what I'm putting together in the short term.

**Comment by briangregoryholmes** [comment]
Live in v7.0.36

**Comment by rohanrajpal** [comment]
> Adding this now. Svelvet will have two new props:
> 
> `edgesAboveNode` `raiseEdgesOnSelect`
> 
> edgesAboveNode can be `false`, `true` or `"all"`. This places edges either below all Nodes, which is the default, above the Nodes it's connected to or above all Nodes. The second option inherently also raises the Edge on selection.
> 
> raiseEdgesOnSelect can be `true`, `"source"` or `"target"`. This raises the z-index of the edge when either node is selected or just the source/target.
> 
> I'm sure this can be more robust and I can add more fine grained control/overrides at the Node/Anchor level, but this is what I'm putting together in the short term.

Works amazing, thanks a ton1
