### ISSUE TITLE
Cannot type in inputs (text, password, etc)

### ISSUE THREAD

**Issue by zacharygriffee** [open-source-labs/Svelvet#319]
I cannot type into inputs like text, password, etc. It is possible my implementation is wrong, or I am missing something in documents to enable this. However, I copied the 'src/example-components/InputNode.svelte' which did not work for me either.

**Custom node**
```
<script>
    let name = "";
</script>
<div>
    <!-- cannot modify this input -->
    <input type="text" bind:value={name} placeholder="enter your name">
</div>
<p>
This is {name} result.
</p>
```

**Node wrap**
```
<script>
    export let component$;
</script>
<Node {...$$props}>
    {#if $component$}
        <svelte:component this={$component$} {...$$props}/>
    {/if}
</Node>
```

![image](https://user-images.githubusercontent.com/5599507/235806702-975300a8-8195-415f-bc59-33e04fd11f27.png)

I even tried to do a z-index to see if there was something 'on top'. But I can click the text box as if I should be able to type into it, but can't type anything into box.

**Comment by briangregoryholmes** [comment]
Fixing right now and adding a test for this functionality. New version should be up within 15 minutes.

**Comment by briangregoryholmes** [comment]
This should be live in v7.0.39. Let me know if it fixed it for you on your end.

**Comment by zacharygriffee** [comment]
Boom! It works on my end! Thanks for the super quick fix!
