### ISSUE TITLE
Optional & customizable title attributes for components

### ISSUE THREAD

**Issue by microdou** [open-source-labs/Svelvet#332]
Currently, Svelvet has hard-coded title attributes in multiple components. It creates simple tooltips upon mouse hovering.

https://github.com/open-source-labs/Svelvet/blob/de07bb1304f64680f2a6fad8caac1c74c2bf88c6/src/lib/components/Anchor/Anchor.svelte#L529
https://github.com/open-source-labs/Svelvet/blob/de07bb1304f64680f2a6fad8caac1c74c2bf88c6/src/lib/containers/Graph/Graph.svelte#L470
https://github.com/open-source-labs/Svelvet/blob/de07bb1304f64680f2a6fad8caac1c74c2bf88c6/src/lib/components/Node/InternalNode.svelte#L304

However, users may want to completely disable the hovering tooltips (to avoid unwanted texts on canvas), or want to custom the texts.

I would suggest making titles optional & customizable.

**Comment by briangregoryholmes** [comment]
Good. Suggestion. This is the default in the latest ^v7.0.45. You can set the title via props.
