### ISSUE TITLE
Unexpected 'edgeDrop' event dispatching from <Svelvet/> component

### ISSUE THREAD

**Issue by Envl** [open-source-labs/Svelvet#361]
Hi, 

According to the [documentation](https://svelvet.mintlify.app/components/svelvet#events), this event should happen under this condition:
> Fires when an Edge connection is started and not completed. Does not fire on drops after a disconnection.

But I've noticed that this event was fired whenever `mouseup` happend on the canvas.

After reading the code, I've noticed the UNCONDITIONED dispatching of this event at the beginning of `onMouseUp`([link to code](https://github.com/open-source-labs/Svelvet/blob/7a8c68f4be417d633da365014e3ea239aec06325/src/lib/containers/Graph/Graph.svelte#L182-L188)) handler in `Graph.svelte`. It might be redundant as in following lines there was another CONDITIONED firing([link to code](https://github.com/open-source-labs/Svelvet/blob/7a8c68f4be417d633da365014e3ea239aec06325/src/lib/containers/Graph/Graph.svelte#L243)) of the same event, which seems align with the documentation better.

As a result, when an unfinished edge was dropped, there would be duplicate `edgeDrop` events.
![image](https://github.com/open-source-labs/Svelvet/assets/9925116/618377f5-448a-4f7f-af83-99abd55a0589)
Reproduction:
https://stackblitz.com/edit/sveltejs-kit-template-default-iksiex?file=src/routes/+page.svelte

**Comment by briangregoryholmes** [comment]
Great catch. We'll have that first extraneous, unconditioned firing removed.
