### ISSUE TITLE
The `node` object in `nodeReleased` event is `undefined` .

### ISSUE THREAD

**Issue by r-wadi** [open-source-labs/Svelvet#367]
Attempting to set the node color on `nodeReleased` event using the following code, that is similer to the example mentioned [here](https://svelvet.mintlify.app/components/node):
````
<script>
  import { Node } from 'svelvet';
  
  function handleClick(e) {
    const { detail } = e;
    detail.node.set.bgColor('red');
  }
</script>

<Node id="55" let:grabHandle let:selected on:nodeClicked="{handleClick}">
  <div use:grabHandle class:selected class="my-component">
    <span>Click Me</span>
  </div>
</Node>
````
results in an error where the `node` is undefined. 

Note: Testing with the `nodeReleased` event since there's already an open issue on the `nodeClicked` event, [ref#357](https://github.com/open-source-labs/Svelvet/issues/357).

**Comment by briangregoryholmes** [comment]
Fixed here: https://github.com/open-source-labs/Svelvet/pull/378

Will be released soon.
