### ISSUE TITLE
Disconnecting from output with multiple edges is broken in 8.0.2

### ISSUE THREAD

**Issue by jindraregal** [open-source-labs/Svelvet#398]
Hello, thanks for this excellent library. I found that in version 8.0.2, there is a bug when disconnecting the edge that comes from the output with multiple outputs. Instead of the right edge disappearing, the edge that was made last from that output disappears. It is reproducible with your demo when upgrading to 8.0.2:

- Disconnect everything
- Connect the single output to multiple inputs
- Try disconnecting in a different order.

https://stackblitz.com/edit/svelvet-v7-qnway8?file=package.json

**Comment by briangregoryholmes** [comment]
Good catch. The each block for edges was not keyed.

Fixed here: https://github.com/open-source-labs/Svelvet/pull/406
