### ISSUE TITLE
icons not loading

### ISSUE THREAD

**Issue by Joshswooft** [open-source-labs/Svelvet#412]
Hi, I was trying to upgrade a project from v7 to v8 and stumbled into an issue with several of the font's not loading. 

Stack blitz link here: https://stackblitz.com/edit/svelvet-v7-jqtqcm?file=src%2Froutes%2F%2Bpage.svelte

**Comment by briangregoryholmes** [comment]
Looking into ways to resolve this, but I believe this is an underlying issue with Svelte/SvelteKit. You'll see that the fonts do load correctly after building.

**Comment by Trackhe** [comment]
> Hello, @briangregoryholmes, So what should I do to make it works in new svelvet versions?

Do you have any errors in the console?
