### ISSUE TITLE
Delete Edge with edgeClick, how?

### ISSUE THREAD

**Issue by Trackhe** [open-source-labs/Svelvet#413]
I want to delete an Edge with clicking on the Edge, but i see only the option to delete the edge with a button in the edge.

And how i can delete the edge with an external button too?

**Comment by Trackhe** [comment]
I added an adition to my PR https://github.com/open-source-labs/Svelvet/pull/403/commits/d095559876b78cecfd8e3e9de5fbe6587b48acde
with that is it easy to delete the edge with edgeClick.

I do something like: 

```
<Edge let:path let:destroy on:hover let:edge enableHover enableDestroyOnClick edgeClick={deleteConnection}><!---->
	<path class="edge" d={path} />
	<button on:click={() => {
		deleteConnection(edge)
		destroy()}} slot="label">
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" ><path class="edge-button-svg" fill="currentColor" d="M19 4h-3.5l-1-1h-5l-1 1H5v2h14M6 19a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7H6v12Z"/></svg>
	</button>
</Edge>
```

maybe also interested here: https://github.com/open-source-labs/Svelvet/issues/414

**Comment by xpluscal** [comment]
Hey @Trackhe how can this be used?
