### ISSUE TITLE
latest version broken due to wrong import

### ISSUE THREAD

**Issue by tobiaskohlbau** [open-source-labs/Svelvet#416]
The latest version ov Svelvet 8.0.5 could not be used as a wrong import was introduced within beb4a3c319e7ea430b800f83cddf8339335f3dde.

```
 ✘ [ERROR] Could not resolve "../../../routes/+page.svelte"

    node_modules/svelvet/dist/components/Anchor/Anchor.svelte:44:17:
      44 │ import Page from "../../../routes/+page.svelte";
         ╵                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Reference:
https://github.com/open-source-labs/Svelvet/blob/beb4a3c319e7ea430b800f83cddf8339335f3dde/src/lib/components/Anchor/Anchor.svelte#L14

**Comment by briangregoryholmes** [comment]
Thanks for catching this. Need to think of a better way to avoid this pre-commit. For right now, I think changing the no-unused-vars eslint rule to `error` instead of `warn` is the best option.
