### ISSUE TITLE
Unable to access Edge events outside of the component

### ISSUE THREAD

**Issue by kirbykatie** [open-source-labs/Svelvet#425]
Due to custom Edges being passed as a prop rather than in a slot, I'm not able to grab a callback or a dispatched event when an edge is clicked. The goal is to display a dialog box allowing the user to edit or delete the edge.

Node and Anchor code:
```
<Node {id} {position} {dimensions} let:grabHandle let:selected on:nodeReleased={onNodeClicked} {connections}>
	<div use:grabHandle class:selected class="person-card">
		<Anchor edge={Edge} multiple dynamic on:connection={e => onConnection(e)}>
		</Anchor>
	</div>
</Node>
```
Edge code:
```
<script>
const dispatch = createEventDispatcher();

const handleEdgeClick = () => {
  dispatch('edgeClicked')
}
</script>

<Edge let:path let:destroy edgeClick={() => handleEdgeClick()}/>
```

These doesn't seem to be a way to grab that dispatched event in the parent code. Additionally, it seems the only way to access the delete method for an edge is by passing a button into the edge's slot. This isn't ideal, but if the `edgeClicked` event could be accessed in the parent, I could at least programmically remove the edge.

**Comment by briangregoryholmes** [comment]
In the latest version of Svelvet, you can pass Edges as children to Anchors. You can also bind to the Edge component and call the destroy method or bind to the Anchor component and call the `disconnect` method. This is an active area, so things are subject to change, but feel free to try it out. Here's a very, very rough Stack Blitz:

https://stackblitz.com/edit/vitejs-vite-jqpyfz?file=package.json,src%2FMyEdge.svelte,src%2FApp.svelte,src%2FDemoNode.svelte

**Comment by kirbykatie** [comment]
Awesome, this is working for me so far. Thanks for the update!!
