### ISSUE TITLE
What does grabHandle do?

### ISSUE THREAD

**Issue by KaiyuanMa** [open-source-labs/Svelvet#429]
```svelte
<Node let:grabHandle bgColor="green" >
    <div class='node-content'>
        content
    </div>
    <div use:grabHandle class="handle">
        handle 
    </div>
</Node>
``` 

If I have handle as grabHandle, why is the node still grabable from anywhere?

This is the description on the site
> Accessed via the let directive. Placed on an element (use:grabHandle) you would like to control movement and selection of the Node.

So I would assume once you add a grabHandle the rest of the node should be not grabable? But rn it is not doing that.
Is there something I am missing?

**Comment by briangregoryholmes** [comment]
You're not missing anything. That was the original intent, but implementing the logic to avoid applying our internal handler based on whether or not the grabHandle was being used externally ended up not being possible in a way that seemed worth it. I may return to it as I clear out other priorities. But it would be a slightly different implementation. The description is a little vague, for sure, and I'll update the docs.

The assumption now is that you'd use the grabHandle to control the Node via some "additional" handle that isn't the Node itself. You could put `pointer-events: "none"` on any elements you want to disable controls for.
