### ISSUE TITLE
Node id's assigned incorrectly when one is removed

### ISSUE THREAD

**Issue by edsunman** [open-source-labs/Svelvet#430]
Hi, when nodes are created from a loop, if a node is removed it looks like the following nodes are named incorrectly.

Example here: https://stackblitz.com/edit/vitejs-vite-a5hmhk?file=src%2FApp.svelte

The nodes have the id's:

 N-1, N-2, N-3, N-4, N-5.

If you click the button remove 3 from the array the nodes have the id's:

N-1, N-2, N-3, N-4

rather than the expected:

N-1, N-2, N-4, N-5

Thanks

**Comment by briangregoryholmes** [comment]
In Svelte, just as in React, you should be keying your rendered elements/components when creating them in this manner. See: https://svelte.dev/tutorial/keyed-each-blocks#

Just put (node) at the end of your each block.

**Comment by edsunman** [comment]
Great, thanks!
