### ISSUE TITLE
allow customization of edge anchoring on node?

### ISSUE THREAD

**Issue by perezd** [open-source-labs/Svelvet#73]
I really love what this project is doing, one feature I'd really love is the ability to designate a "side" of the node to anchor an edge to  (top/bottom/left/right). Currently it seems like one can only assume top down which is somewhat limiting from a drawing space.

```js
{ 
  id: "e1-3", 
  source: 1, 
  target: 3, 
  type: "straight",
  anchors: {
    source: "left",
    target: "top"
  }
}
```

Thoughts?

**Comment by anulepau** [comment]
this is an excellent idea and something we have definitely thought of adding! thank you so much. we'll let you know when we've updated the npm package to include this feature, and definitely feel free to suggest any ideas / contribute to the code if you feel called to!

**Comment by pseamusmcdonald** [comment]
> I really love what this project is doing, one feature I'd really love is the ability to designate a "side" of the node to anchor an edge to (top/bottom/left/right). Currently it seems like one can only assume top down which is somewhat limiting from a drawing space.

Hey Derek,

I've added this feature to my fork and created a pull request!

Thanks for bringing it up.

- Seamus

**Comment by perezd** [comment]
Awesome work!!
