### ISSUE TITLE
 Is it possible to export to interactive file formats such as xmind and html

### ISSUE THREAD

**Issue by rockcitystore** [open-source-labs/Svelvet#78]
Is it possible to export to interactive file formats such as xmind and html

**Comment by andrew-widjaja** [comment]
We currently don't have any file exports available, but we can definitely keep that in mind as others have also suggested exporting in other file formats. Thanks!

**Comment by taylien96** [comment]
you can now download and upload diagrams via the shareable prop as of svelvet 5.0 ! check the documentation
