### ISSUE TITLE
Interactive Node creation and linking

### ISSUE THREAD

**Issue by rajasegar** [open-source-labs/Svelvet#81]
Is it possible to create nodes interactively by right clicking in the canvas and choosing a node type? 
Some thing similar to what `rete.js` does...
https://rete.js.org/
There were some attempts to create a Svelte render plugin here
https://github.com/c0bra/rete-svelte-render-plugin
BTW, thanks for this awesome tool 👍

**Comment by Explosion-Scratch** [comment]
And API methods for this, like listening for node updates, added, move, adding nodes via JS as well, having custom HTML inside the nodes

**Comment by emmanotly** [comment]
Hi @rajasegar !

Thank you for using Svelvet and making this awesome suggestion! I am on the Svelvet 5.0 team and am happy to let you know that we have successfully made this feature and will continue testing this feature up until we launch to make sure interactive node linking and creation is as good as it could possibly be!

We are getting excited about our launch early next year!

We look forward to your continued feedback after you get some time to play with this new feature!

Cheers!

**Comment by timmylem01** [comment]
A little sneak peak of interactive node creation and linking 👀 🤫 
![demo](https://user-images.githubusercontent.com/103241084/208499835-c0193e2a-4b5c-4432-9906-4e14bcd524ac.gif)

**Comment by taylien96** [comment]
This is now in svelvet 5.0, check the documentation on the website!!

**Comment by Explosion-Scratch** [comment]
FYI the demo (on the website) isn't working, glad you guys are working on and improving this project though!

**Comment by timmylem01** [comment]
@Explosion-Scratch can you specify which demo?

**Comment by taylien96** [comment]
It is disabled on the demo if you're refering to the one on the front page

**Comment by Explosion-Scratch** [comment]
Huh, went to record to try to reproduce and everything seems to be working, if I recall correctly there was a white screen, I waited for a few seconds then there was a console error but I don't remember what it was. I guess it doesn't matter much though because I can't seem to reproduce the error, sorry!

**Comment by timmylem01** [comment]
Phew, thank god! Haha all jokes aside let us know if there are any bugs that do arise!
