### ISSUE TITLE
Data change reactivity (question)

### ISSUE THREAD

**Issue by sanderjson** [open-source-labs/Svelvet#88]
How to make the node graph reactive to data change?

[Example Svelte REPL] (https://svelte.dev/repl/0e9cb2fb95224a5cb049e0e8c945885f?version=3.48.0)

**Comment by DavidBernal** [comment]
@oslabs-beta have you this issue in your backlog?

**Comment by TensionCoding** [comment]
We are happy to announce the release of version 2.0. If you go to your example Svelte REPL link, the button will now generate a new Node. We are still writing the change log. Thank you for opening this issue.

**Comment by TensionCoding** [comment]
This is issue is resolved as of [PR 100](https://github.com/open-source-labs/Svelvet/pull/100)
