### ISSUE TITLE
Regression/bug in 1.0.3 not present in 1.0.2 : continued dragging after mouse click release outside of node

### ISSUE THREAD

**Issue by Thomasorus** [open-source-labs/Svelvet#91]
When you zoom out and drag and drop, you have a delta between the distance travelled by your mouse and the distance travelled by the node. This is known and discussed in [64](https://github.com/open-source-labs/Svelvet/issues/64).

But the 1.0.3 release introduced a bug related to it: if you zoom out, click to drag, drag until your mouse is out of the node, then release, the node will continue moving with your mouse.

How to reproduce:
- Go to https://svelvet.io/
- In the first demo, zoom out, drag a node until the pointer is out of the node, release the click.
- Move the mouse, the node will continue moving.
- You can reproduce this problem with multiple nodes.

It was not present in 1.0.2:
- Go to https://svelvet.io/docs/core-concepts/
- In the demo, zoom out, drag a node until the pointer is out of the node, release the click.
- Move the mouse, the node won't move.

If you go directly to the [CodeSandbox](https://codesandbox.io/s/core-concepts-yixl8c?from-embed) you will see this demo uses 1.0.2. Change the version to 1.0.3 and the bug will happen. That's how I discovered it was happening.

Might be related to [this PR](https://github.com/open-source-labs/Svelvet/commit/f820fa42b33ef03a7c9a0a776cd5386eadb872e4).

**Comment by TensionCoding** [comment]
This issue has been fixed as of [PR 100](https://github.com/open-source-labs/Svelvet/pull/100).
