### ISSUE TITLE
Dynamic change of nodes and edges

### ISSUE THREAD

**Issue by bogdankol** [open-source-labs/Svelvet#96]
Hi :) I think there is a problem with dynamic change of data in Svelvet. For example: I created two array of nodes and two arrays of edges, there is a button which changes a value of nodesToRender variable (which is array of nodes to render), when I press it - I can see in console that nodesToRender array changed, but Svelvet didn't render these new nodes.

Example code: https://svelte.dev/repl/327b6dbe12584691956698ae28a3fe6b?version=3.49.0

**Comment by TensionCoding** [comment]
We have just updated to version 2.0 as of today!!! If you visit the link, you will see that your button now works. Enjoy the update. We are still writing the change log. Thank you so much for your continued interest in the project
